protogen -sfcc.p analyze.c cglbdec.c cmain.c decl.c declass.c
protogen -asfcc.p error.c expr.c floatexp.c func.c mangle.c
protogen -asfcc.p getsym.c init.c intexpr.c list.c memmgt.c     
protogen -asfcc.p optimize.c preproc.c searchkw.c   
protogen -asfcc.p stmt.c symbol.c types.c
protogen -sfcc68.p gexpr68.c gstmt68.c outas68.c peep68.c reg68.c an68.c conf68.c
protogen -sfcc386.p gexpr386.c gstmt386.c outas386.c peep386.c reg386.c an386.c conf386.c
protogen -asfcc68.p inasm68.c
iprotogen -asfcc386.p inasm386.c