CC = ccn /c
CFLAGS = /v 

all:
	$(CC) $(CFLAGS) -D__stdcall c_parser.c c_lex.c alloc.c c_list.c c_preval.c c_preprc.c dllmain.c
	$(CC) $(CFLAGS) test.c parser.lib
	$(CC) $(CFLAGS) codecomp.c parser.lib

clean:
	rm -f parser
