CC = bcc32
CFLAGS = /v -w-

all:
	$(CC) $(CFLAGS) /tWDE -eparser c_parser.c c_lex.c alloc.c c_list.c c_preval.c c_preprc.c dllmain.c
	$(CC) $(CFLAGS) -etest test.c parser.lib
	$(CC) $(CFLAGS) -eccmp codecomp.c parser.lib

clean:
	rm -f parser
